package org.mapper;

import java.util.List;
import java.util.Map;

import org.bean.Drug;

public interface DrugMapper {
	
	List<Drug> getDrugAddInfo(Drug bean);		//获取药品列表
	int deleteZdtraInfo(Drug bean);				//删除药品信息
	int updateDrugInfo(Drug bean);				//更新药品信息
	Drug getIsHave(Drug bean);					//判断药品信息是否存在
	int addDrugInfo(Drug bean);					//添加药品信息
	List<Drug> getSelectType();					//获取计量单位下拉框内容
	List<Drug> selectPynTYpe();					//获取拼音码下拉框内容
	List<Drug> selectDnTYpe(Map<String, Object> map);	//获取药品名称下拉框
	List<Drug> getDrugInfo(Map<String, Object> map);	//根据拼音吗和药品信息获取对应的药品信息
	List<Drug> getDInfo(Map<String, Object> map);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug
     *
     * @mbggenerated Tue Apr 17 09:45:22 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug
     *
     * @mbggenerated Tue Apr 17 09:45:22 CST 2018
     */
    int insert(Drug record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug
     *
     * @mbggenerated Tue Apr 17 09:45:22 CST 2018
     */
    int insertSelective(Drug record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug
     *
     * @mbggenerated Tue Apr 17 09:45:22 CST 2018
     */
    Drug selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug
     *
     * @mbggenerated Tue Apr 17 09:45:22 CST 2018
     */
    int updateByPrimaryKeySelective(Drug record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug
     *
     * @mbggenerated Tue Apr 17 09:45:22 CST 2018
     */
    int updateByPrimaryKey(Drug record);
	
	
	
	
	
	
	
	





	

	
}