package org.mapper;

import java.util.List;
import java.util.Map;

import org.bean.Ruku;

import utils.JsonResult;

public interface RukuMapper {
	
	List<Ruku> getDrugInInfo(Ruku bean);		//获取入库表信息
	int updateDrugInInfo(Ruku bean);			//更新入库表信息
	int deleteDrugInInfo(Ruku bean);			//根据拼音码，药品名称，药品批号以及批准文号删除对应的数据
	Ruku getIsHave(Ruku bean);					//判断入库表中是否存在
	int addDrugInInfo(Ruku bean);				//添加药品信息进入入库表
	int setSfth(Ruku ruku);						//修改是否退货标志
	List<Ruku> getRukuAmount(Map<String, Object> map);		//获取入库总额
	List<Ruku> getUSDrugInfo(Ruku bean);		//获取未出售的药品信息
	int setSfxs(Ruku ruku);						//修改是否销售标志
	List<Ruku> getRukAmount(Map<String, Object> map2);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ruku
     *
     * @mbggenerated Thu Apr 19 16:37:39 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ruku
     *
     * @mbggenerated Thu Apr 19 16:37:39 CST 2018
     */
    int insert(Ruku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ruku
     *
     * @mbggenerated Thu Apr 19 16:37:39 CST 2018
     */
    int insertSelective(Ruku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ruku
     *
     * @mbggenerated Thu Apr 19 16:37:39 CST 2018
     */
    Ruku selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ruku
     *
     * @mbggenerated Thu Apr 19 16:37:39 CST 2018
     */
    int updateByPrimaryKeySelective(Ruku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ruku
     *
     * @mbggenerated Thu Apr 19 16:37:39 CST 2018
     */
    int updateByPrimaryKey(Ruku record);
	
	
	
	
	
	
	
	
	







	

	
}