package org.mapper;

import java.util.List;

import org.bean.Zdfy;

public interface ZdfyMapper {
	List<Zdfy> getZdtraInfo(Zdfy bean);		//获取字段翻译库的列表
	int deleteZdtraInfo(Zdfy bean);			//删除某个字段翻译的数据	
	int updateZdtraInfo(Zdfy bean);			//编辑某个字段翻译的数据
	Zdfy getIsHave(Zdfy bean);				//检查字段是否存在
	int addZdtra(Zdfy bean);				//添加字段
	
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zdfy
     *
     * @mbggenerated Thu Apr 12 20:04:19 CST 2018
     */
    int insert(Zdfy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zdfy
     *
     * @mbggenerated Thu Apr 12 20:04:19 CST 2018
     */
    int insertSelective(Zdfy record);
	
	
	
	





	

	
}